rails-basics-ru/models/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  # BEGIN
  resources :articles, only: %i[index show]
  # END
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails-basics-ru/models/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-basics-ru/models/app/models/article.rb
class Article < ApplicationRecord
end

rails-basics-ru/models/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

rails-basics-ru/models/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end
end

rails-basics-ru/models/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

rails-basics-ru/models/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

rails-basics-ru/models/app/helpers/articles_helper.rb
module ArticlesHelper
end

rails-basics-ru/models/app/views/articles/index.html.erb
<h1>Articles</h1>
<% @articles.each do |article| %>
  <h3><li><%= link_to article.title, article_path(article) %></li></h3>
<% end %>

rails-basics-ru/models/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>

rails-basics-ru/models/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

rails-basics-ru/models/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Models</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
  <nav>
    <ul>
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Articles', articles_path %></li>
    </ul>
  </nav>
    <%= yield %>
  </body>
</html>